### ISSUE TITLE
I have created a hello.txt file on my micro:bit and try to retrieve iton my computer through a Python script using microfs API. 

### ISSUE THREAD

**Issue by geraldineolivier** [ntoll/microfs#34]
I have created a hello.txt file on my micro:bit and try to retrieve iton my computer through a Python script using microfs API. 

Here is my Pthon script
import microfs
import os
cwd = os.getcwd()
list_files_on_ubit = microfs.ls()
print(list_files_on_ubit)
microfs.get('hello.txt')

I have the following error:
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "C:\Users\Geraldine OLIVIER\AppData\Roaming\Python\Python37\site-packages\microfs.py", line 297, in get
    assert out.startswith(b"b'")
AssertionError

The "out" variable is indeed very strange b''

I have checked my hello.txt file by retrieving it using mu editor, and it seems completely OK (I have enclosed it)
[hello.txt](https://github.com/ntoll/microfs/files/7775960/hello.txt)

Thanks for your help!

**Comment by ntoll** [comment]
Hi @geraldineolivier and Merry Christmas.

What version of MicroPython and what version of micro:bit do you have..? Please ensure you have the latest available version of MicroPython for the type of micro:bit you have.

Do let me know how you get on.

**Comment by geraldineolivier** [comment]
MicroPython v1.15-64-g1e2f0d280 on 2021-06-30; micro:bit v2.0.0 with nRF52833

**Comment by geraldineolivier** [comment]
Thanks for your answer and merry christmas to you too!
I have updated the hardware on my microbit using this reference https://microbit.org/get-started/user-guide/firmware/  but the embedded MicroPython is still the same. It is not the latest version of MicroPython which is apparently 1.17, but I don't know how to update the embedded MicroPython on a micro:bit.
I give you the whole code so that you can test:  there are 2 micro-bit communicating, a sender and a receiver. The receiver writes a file "hello.txt" on its system. I try to write a Python code using microfs  to retrieve this file on my computer. 
I have put the code below. File "hello.txt" is indeed on the receiving micro:bit and I can see it using microfs command ls. But when getting the file, the out string is b'' and causes a crash on line 296 of microfs.py

I have printed out and commands to see what's going on:
out= b''
command= ["try:\n from microbit import uart as u\nexcept ImportError:\n try:\n  from machine import UART\n  u = UART(0, 115200)\n except Exception:\n  try:\n   from sys import stdout as u\n  except Exception:\n   raise Exception('Could not find UART module in device.')", "f = open('hello.txt', 'rb')", 'r = f.read', 'result = True', 'while result:\n result = r(32)\n if result:\n  u.write(repr(result))', 'f.close()']


### receiver.py, on the receiving micro:bit ###
import radio


radio.on()


with open('hello.txt', 'w') as my_file:
    while True:
        value = radio.receive()
        if (value == "stop"):
            my_file.close()
            break
        if (value != None):
            print(value)
            my_file.write(str(value) + "\n")

### sender.py on the sending micro:bit###

import microbit
import radio
import random

radio.on()

while True:

    if microbit.button_a.is_pressed():
        temp = random.randint(0, 9)
        print(temp)
        radio.send(str(temp))
        microbit.sleep(500)

    if microbit.button_b.is_pressed():
        radio.send("stop")
        break

### code running on my computer to retrieve file "hello.txt" from receiving microbit ###
import microfs
import os

cwd = os.getcwd()
list_files_on_ubit = microfs.ls()
print(list_files_on_ubit)
microfs.get('hello.txt')

**Comment by carlosperate** [comment]
I've run into this issue recently as well, I think it's because microFS expects all the returned strings to start with `b'` and end in `'`, but sometimes they use the double quotes, as the content inside might use single quotes.
I'll raise a PR to fix this.

**Comment by AirplanegoBrr** [comment]
Here is a temp fix that I found (if anyone gets this issue)
This replaces lines 296 -> 297 in the microfs.py file
```py
    if (out.startswith(b"b'") and out.endswith(b"'")):
        assert out.startswith(b"b'")
        assert out.endswith(b"'")
    if (out.startswith(b'b"') and out.endswith(b'"')):
        assert out.startswith(b'b"')
        assert out.endswith(b'"')
```
(Just a heads up I don't know if this is **100% the proper way**, I would wait for devs to make official PR/Edits. Soon hopefully)

**Comment by carlosperate** [comment]
Thanks @AirplanegoBrr! 

I have a half finished PR to raise (mostly need to write some tests). As the file reads are done in 64 byte blocks we end up with multiple byte strings in a single `out` variable, and since each can have different quote marks the first and last one don't neccesarily match.
Ultimately I don't think we need to care too much about it, as long as it is a collection of byte strings that can be evaled into a single string.
